swagger: "2.0"
host: accounts.stage.mozaws.net
info:
  title: FxA Content Server
  description: The content Server of FxA
  contact:
    name: Ryan Kelly
    email: ryan@someemail.com
  license:
    name: MPL v2.0
    url: https://www.mozilla.org/en-US/MPL/2.0/
  version: 0.36.3
  termsOfService: https://latest.dev.lcip.org/legal/terms
  x-mozilla-services:
    homepage: https://github.com/mozilla/fxa-content-server
    commit: 25dedeb0b1f2d5212f34e41ed17317bc5fbf5477
    l10n: 412fdf2ec9

paths:
    /__heartbeat__:
        get:
            description: Sanity check
            produces:
            - application/json
            responses:
                '200':
                    description: The app is up
